### ISSUE TITLE
[Tickets] Two requests (roles/message)

### ISSUE THREAD

**Issue by sLmp20** [vertyco/vrt-cogs#199]
**Is your feature request related to a problem? Please describe.**
No, neither request is an issue with the cog. The first is allowing support roles to be panel specific, and the second is adding a command to remove the message at the start of every ticket entirely. 

**Describe the solution you'd like**
I'm not sure of how simple a solution, but allowing support roles to be panel specific would be fantastic. For the other I think just a command to remove the start message would be really helpful for me. 

**Describe alternatives you've considered**
i'm not sure of any alternatives for either of these. 

**Additional context**
I've been using this cog since before it was verified on the index, and I haven't had a single complaint. Even if these aren't added I've been very happy with all of the additions i've seen over the past year and a half or so. So, thank you.

**Comment by vertyco** [comment]
You can already set a panel specific role via `[p]tickets panelrole <panel_name> <role> [mention=False]`

`[p]tset supportrole` applies to all panels whereas that command is for specific panels.

As for having a ticket opened with no message at all, there isn't an easy way to implement it at the moment due to the cog needing somewhere to put the close button.

**Comment by sLmp20** [comment]
is the close button required? or could you make it so you can opt out?

**Comment by vertyco** [comment]
Right now it is hard coded to always have a close button with no opt out. This was a design choice to make the cog more user friendly, hence the default message whenever a custom one isn't set. I will probably need to rewrite this cog at some point because the feature creep is making it start to get messy. Not ETA on when i'd be able to rewrite it as life has been extremely busy lately.

**Comment by sLmp20** [comment]
no problem at all, thanks for taking a look. I hope you have a chance to get to it at some point.

**Comment by vertyco** [comment]
Closing this as it isnt something that will get implemented in the forseeable future
