### ISSUE TITLE
[Feature Request] [Tickets] Timed ticket closes

### ISSUE THREAD

**Issue by EternalllZM** [vertyco/vrt-cogs#44]
A command for setting a timer on closure/no response would be beneficial. Sometimes you provide a solution to a member and they carry it out without updating the ticket. This increases overhead and the responsibility of ensuring the ticket is ok to close on the support staff.

This change proposes a command that notifies within the ticket a solution has been proposed/assumed completed and the ticket will close in X amount of time unless they respond explaining what the issue still being experienced is. If the user responds, it will abort the closure.

Similarly related, I was wondering if there was any way to view commands available within the thread such as `[p]close`. There doesn't seem to be a clear way to do this.

**Comment by vertyco** [comment]
updated with most recent commit. if auto-close is on. the ticket opener will be warned 20 minutes before the ticket is closed(since that is how often the loop runs)

As for the close command. The default ticket message tells the user whether they can close the ticket or not. It is up to the admin formatting the custom message to decide how they wanna let their user's know what commands they can use.
